from .animation import AnimationView
from .any_content_type_message import AnyContentTypeMessageView
from .audio import AudioView
from .connected_website import ConnectedWebsiteView
from .contact import ContactView
from .delete_chat_photo import DeleteChatPhotoView
from .dice import DiceView
from .document import DocumentView
from .game import GameView
from .group_chat_created import GroupChatCreatedView
from .invoice import InvoiceView
from .left_chat_member import LeftChatMemberView
from .location import LocationView
from .migrate_from_chat_id import MigrateFromChatIdView
from .migrate_to_chat_id import MigrateToChatIdView
from .new_chat_members import NewChatMembersView
from .new_chat_photo import NewChatPhotoView
from .new_chat_title import NewChatTitleView
from .passport_data import PassportDataView
from .photo import PhotoView
from .pinned_message import PinnedMessageView
from .poll import PollMessageView
from .sticker import StickerView
from .successful_payment import SuccessfulPaymentView
from .text import TextView
from .venue import VenueView
from .video import VideoView
from .video_note import VideoNoteView
from .voice import VoiceView
